import { describe, it, expect } from 'vitest';
import {
  findForbiddenWords,
  removeForbiddenWords,
  cleanTags,
  validateAndCleanContent,
  filterAIResponse,
  FORBIDDEN_WORDS,
} from './contentQualityFilter';

describe('Content Quality Filter', () => {
  describe('findForbiddenWords', () => {
    it('should detect watermark-related words', () => {
      expect(findForbiddenWords('Image with watermark overlay')).toContain('watermark');
      expect(findForbiddenWords('Company logo visible')).toContain('logo');
      expect(findForbiddenWords('Copyrighted material')).toContain('Copyrighted');
    });

    it('should detect multiple forbidden words', () => {
      const result = findForbiddenWords('Watermarked image with logo and signature');
      expect(result.length).toBeGreaterThanOrEqual(3);
    });

    it('should be case insensitive', () => {
      expect(findForbiddenWords('WATERMARK').length).toBeGreaterThan(0);
      expect(findForbiddenWords('WaterMark').length).toBeGreaterThan(0);
      expect(findForbiddenWords('watermark').length).toBeGreaterThan(0);
    });

    it('should return empty array for clean text', () => {
      expect(findForbiddenWords('Beautiful sunset over mountains')).toHaveLength(0);
    });

    it('should detect stock photo references', () => {
      expect(findForbiddenWords('Stock photo of nature').length).toBeGreaterThan(0);
      expect(findForbiddenWords('Sample image for testing').length).toBeGreaterThan(0);
    });

    // Stock platform names tests
    it('should detect Shutterstock references', () => {
      expect(findForbiddenWords('Image from Shutterstock').length).toBeGreaterThan(0);
      expect(findForbiddenWords('shutter stock photo').length).toBeGreaterThan(0);
    });

    it('should detect Getty Images references', () => {
      expect(findForbiddenWords('Getty Images photo').length).toBeGreaterThan(0);
      expect(findForbiddenWords('getty photo').length).toBeGreaterThan(0);
    });

    it('should detect iStock references', () => {
      expect(findForbiddenWords('iStock photo').length).toBeGreaterThan(0);
      expect(findForbiddenWords('istockphoto image').length).toBeGreaterThan(0);
    });

    it('should detect Adobe Stock references', () => {
      expect(findForbiddenWords('Adobe Stock image').length).toBeGreaterThan(0);
      expect(findForbiddenWords('adobestock photo').length).toBeGreaterThan(0);
    });

    it('should detect other stock platforms', () => {
      expect(findForbiddenWords('Alamy photo').length).toBeGreaterThan(0);
      expect(findForbiddenWords('Dreamstime image').length).toBeGreaterThan(0);
      expect(findForbiddenWords('Depositphotos picture').length).toBeGreaterThan(0);
      expect(findForbiddenWords('123RF stock').length).toBeGreaterThan(0);
      expect(findForbiddenWords('Pond5 video').length).toBeGreaterThan(0);
      expect(findForbiddenWords('Envato Elements asset').length).toBeGreaterThan(0);
    });

    it('should detect free stock platforms', () => {
      expect(findForbiddenWords('Pixabay free image').length).toBeGreaterThan(0);
      expect(findForbiddenWords('Unsplash photo').length).toBeGreaterThan(0);
      expect(findForbiddenWords('Pexels picture').length).toBeGreaterThan(0);
    });

    // AI-generated terms tests
    it('should detect AI generated terms', () => {
      expect(findForbiddenWords('AI generated image').length).toBeGreaterThan(0);
      expect(findForbiddenWords('AI-generated artwork').length).toBeGreaterThan(0);
      expect(findForbiddenWords('ai-created photo').length).toBeGreaterThan(0);
    });

    it('should detect AI tool names', () => {
      expect(findForbiddenWords('Midjourney art').length).toBeGreaterThan(0);
      expect(findForbiddenWords('Stable Diffusion image').length).toBeGreaterThan(0);
      expect(findForbiddenWords('DALL-E generated').length).toBeGreaterThan(0);
      expect(findForbiddenWords('dalle artwork').length).toBeGreaterThan(0);
    });

    it('should detect synthetic and machine generated terms', () => {
      expect(findForbiddenWords('Synthetic image').length).toBeGreaterThan(0);
      expect(findForbiddenWords('Machine generated art').length).toBeGreaterThan(0);
      expect(findForbiddenWords('Computer generated graphics').length).toBeGreaterThan(0);
    });

    it('should detect AI technology terms', () => {
      expect(findForbiddenWords('Neural network created').length).toBeGreaterThan(0);
      expect(findForbiddenWords('Deep learning model').length).toBeGreaterThan(0);
      expect(findForbiddenWords('Generative AI art').length).toBeGreaterThan(0);
    });

    it('should detect various AI attribution patterns', () => {
      expect(findForbiddenWords('Generated by AI').length).toBeGreaterThan(0);
      expect(findForbiddenWords('Created with AI').length).toBeGreaterThan(0);
      expect(findForbiddenWords('Made using AI').length).toBeGreaterThan(0);
    });
  });

  describe('removeForbiddenWords', () => {
    it('should remove watermark word', () => {
      const result = removeForbiddenWords('Image with watermark visible');
      expect(result.toLowerCase()).not.toContain('watermark');
      expect(result).toContain('Image');
      expect(result).toContain('visible');
    });

    it('should remove logo word', () => {
      const result = removeForbiddenWords('Company logo on product');
      expect(result.toLowerCase()).not.toContain('logo');
    });

    it('should clean up extra spaces', () => {
      const result = removeForbiddenWords('Text with watermark here');
      expect(result).not.toContain('  '); // No double spaces
    });

    it('should preserve clean text', () => {
      const original = 'Beautiful mountain landscape at sunset';
      expect(removeForbiddenWords(original)).toBe(original);
    });

    it('should remove stock platform names', () => {
      const result = removeForbiddenWords('Beautiful Shutterstock sunset image');
      expect(result.toLowerCase()).not.toContain('shutterstock');
    });

    it('should remove AI terms', () => {
      const result = removeForbiddenWords('AI generated beautiful landscape');
      expect(result.toLowerCase()).not.toContain('ai generated');
      expect(result.toLowerCase()).not.toContain('ai-generated');
    });

    it('should remove Midjourney references', () => {
      const result = removeForbiddenWords('Midjourney art beautiful sunset');
      expect(result.toLowerCase()).not.toContain('midjourney');
    });
  });

  describe('cleanTags', () => {
    it('should remove tags containing forbidden words', () => {
      const tags = 'nature, watermark, sunset, logo, mountains';
      const result = cleanTags(tags);
      expect(result).not.toContain('watermark');
      expect(result).not.toContain('logo');
      expect(result).toContain('nature');
      expect(result).toContain('sunset');
      expect(result).toContain('mountains');
    });

    it('should preserve clean tags', () => {
      const tags = 'nature, sunset, mountains, travel';
      expect(cleanTags(tags)).toBe('nature, sunset, mountains, travel');
    });

    it('should handle empty input', () => {
      expect(cleanTags('')).toBe('');
    });

    it('should remove stock platform name tags', () => {
      const tags = 'nature, shutterstock, sunset, getty, mountains';
      const result = cleanTags(tags);
      expect(result.toLowerCase()).not.toContain('shutterstock');
      expect(result.toLowerCase()).not.toContain('getty');
    });

    it('should remove AI-related tags', () => {
      const tags = 'nature, ai-generated, sunset, midjourney, mountains';
      const result = cleanTags(tags);
      expect(result.toLowerCase()).not.toContain('ai-generated');
      expect(result.toLowerCase()).not.toContain('midjourney');
    });
  });

  describe('validateAndCleanContent', () => {
    it('should detect issues in all fields', () => {
      const result = validateAndCleanContent({
        title: 'Image with watermark',
        description: 'Photo with visible logo',
        tags: 'nature, watermark, sunset',
        prompt: 'Create image with copyright notice',
      });

      expect(result.hasIssues).toBe(true);
      expect(result.issues.length).toBeGreaterThan(0);
    });

    it('should auto-clean all fields', () => {
      const result = validateAndCleanContent({
        title: 'Beautiful watermark sunset',
        description: 'Amazing logo photo',
        tags: 'nature, watermark, sunset',
        prompt: 'Create beautiful copyright image',
      });

      expect(result.autoCleanedData.title.toLowerCase()).not.toContain('watermark');
      expect(result.autoCleanedData.description.toLowerCase()).not.toContain('logo');
      expect(result.autoCleanedData.tags.toLowerCase()).not.toContain('watermark');
      expect(result.autoCleanedData.prompt.toLowerCase()).not.toContain('copyright');
    });

    it('should return no issues for clean content', () => {
      const result = validateAndCleanContent({
        title: 'Beautiful mountain sunset',
        description: 'Stunning landscape photography',
        tags: 'nature, sunset, mountains',
        prompt: 'Create beautiful landscape image',
      });

      expect(result.hasIssues).toBe(false);
      expect(result.issues).toHaveLength(0);
    });

    it('should clean stock platform references from all fields', () => {
      const result = validateAndCleanContent({
        title: 'Shutterstock style sunset',
        description: 'Getty Images quality photo',
        tags: 'nature, adobe stock, sunset',
        prompt: 'Create iStock quality image',
      });

      expect(result.hasIssues).toBe(true);
      expect(result.autoCleanedData.title.toLowerCase()).not.toContain('shutterstock');
      expect(result.autoCleanedData.description.toLowerCase()).not.toContain('getty');
      expect(result.autoCleanedData.tags.toLowerCase()).not.toContain('adobe stock');
    });

    it('should clean AI terms from all fields', () => {
      const result = validateAndCleanContent({
        title: 'AI generated sunset',
        description: 'Midjourney style artwork',
        tags: 'nature, stable diffusion, sunset',
        prompt: 'DALL-E style image',
      });

      expect(result.hasIssues).toBe(true);
      expect(result.autoCleanedData.title.toLowerCase()).not.toContain('ai generated');
      expect(result.autoCleanedData.description.toLowerCase()).not.toContain('midjourney');
      expect(result.autoCleanedData.tags.toLowerCase()).not.toContain('stable diffusion');
    });
  });

  describe('filterAIResponse', () => {
    it('should filter and flag response with issues', () => {
      const result = filterAIResponse({
        prompt: 'Create image with watermark',
        title: 'Logo design concept',
        description: 'Beautiful stock photo',
        tags: 'nature, watermark, sunset',
        category: 'Nature',
      });

      expect(result.wasFiltered).toBe(true);
      expect(result.filteredWords.length).toBeGreaterThan(0);
      expect(result.prompt.toLowerCase()).not.toContain('watermark');
      expect(result.title.toLowerCase()).not.toContain('logo');
      expect(result.tags.toLowerCase()).not.toContain('watermark');
    });

    it('should preserve category', () => {
      const result = filterAIResponse({
        prompt: 'Create image',
        title: 'Mountain sunset',
        description: 'Beautiful landscape',
        tags: 'nature, sunset',
        category: 'Nature',
      });

      expect(result.category).toBe('Nature');
    });

    it('should flag clean response as not filtered', () => {
      const result = filterAIResponse({
        prompt: 'Create beautiful sunset image',
        title: 'Golden mountain sunset',
        description: 'Stunning landscape photography',
        tags: 'nature, sunset, mountains',
      });

      expect(result.wasFiltered).toBe(false);
      expect(result.filteredWords).toHaveLength(0);
    });

    it('should filter all stock platform names', () => {
      const result = filterAIResponse({
        prompt: 'Shutterstock style image',
        title: 'Getty quality photo',
        description: 'iStock premium artwork',
        tags: 'adobe stock, alamy, dreamstime',
      });

      expect(result.wasFiltered).toBe(true);
      expect(result.prompt.toLowerCase()).not.toContain('shutterstock');
      expect(result.title.toLowerCase()).not.toContain('getty');
      expect(result.description.toLowerCase()).not.toContain('istock');
    });

    it('should filter all AI-generated terms', () => {
      const result = filterAIResponse({
        prompt: 'AI generated masterpiece',
        title: 'Midjourney artwork',
        description: 'Stable Diffusion creation',
        tags: 'dall-e, neural network, synthetic',
      });

      expect(result.wasFiltered).toBe(true);
      expect(result.prompt.toLowerCase()).not.toContain('ai generated');
      expect(result.title.toLowerCase()).not.toContain('midjourney');
      expect(result.description.toLowerCase()).not.toContain('stable diffusion');
    });
  });

  describe('FORBIDDEN_WORDS comprehensive coverage', () => {
    it('should have all major stock platforms in forbidden list', () => {
      const majorPlatforms = [
        'shutterstock', 'getty', 'istock', 'adobe stock', 'alamy',
        'dreamstime', 'depositphotos', '123rf', 'pond5', 'envato'
      ];
      
      for (const platform of majorPlatforms) {
        expect(FORBIDDEN_WORDS.some(w => w.toLowerCase().includes(platform.toLowerCase()))).toBe(true);
      }
    });

    it('should have all AI terms in forbidden list', () => {
      const aiTerms = [
        'ai generated', 'midjourney', 'stable diffusion', 'dall-e',
        'synthetic', 'neural network', 'deep learning'
      ];
      
      for (const term of aiTerms) {
        expect(FORBIDDEN_WORDS.some(w => w.toLowerCase().includes(term.toLowerCase()))).toBe(true);
      }
    });

    it('should have all watermark terms in forbidden list', () => {
      const watermarkTerms = [
        'watermark', 'logo', 'copyright', 'signature', 'branded'
      ];
      
      for (const term of watermarkTerms) {
        expect(FORBIDDEN_WORDS.some(w => w.toLowerCase().includes(term.toLowerCase()))).toBe(true);
      }
    });
  });
});
